name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t tmcarrara/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true tmcarrara/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-kubernetes-472615

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t tmcarrara/multi-client:latest -t tmcarrara/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t tmcarrara/multi-server:latest -t tmcarrara/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t tmcarrara/multi-worker:latest -t tmcarrara/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push tmcarrara/multi-client:latest
          docker push tmcarrara/multi-server:latest
          docker push tmcarrara/multi-worker:latest

          docker push tmcarrara/multi-client:${{ env.SHA }}
          docker push tmcarrara/multi-server:${{ env.SHA }}
          docker push tmcarrara/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=tmcarrara/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=tmcarrara/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=tmcarrara/multi-worker:${{ env.SHA }}
